apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-from-jenkins
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        # ✅ AMAN: Menggunakan VPC Endpoint (Internal Network)
        # Format: registry-vpc.<region>.aliyuncs.com/<namespace>/<repo-name>:<tag>
        image: registry-vpc.ap-southeast-5.aliyuncs.com/gandes-test/gandes-github:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      # Wajib ada agar ACK bisa pull image dari ACR Private
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080